tasks:
  - before: |
      apt-get install -y graphviz graphviz-dev;
      apt-get install -y python3-dev
      pip install pre-commit
      pre-commit install --install-hooks
  - init: pip install .
image: python:3.9-slim
vscode:
  extensions:
    - ms-toolsai.jupyter
