tasks:
  - before: |
      sudo apt-get install -y graphviz graphviz-dev;
      sudo apt-get install -y python3-dev
      pyenv install 3.9.10
      pyenv global 3.9.10
      pip install pre-commit
      pre-commit install
  - init: pip install .
vscode:
  extensions:
    - ms-python.python