language: python
python:
  - "3.8.2"
jobs:
  include:
    - stage: "test"
      name: "pytest"
      install:
        - python setup.py install
      script: pytest
    - stage: "test"
      name: "pre-commit"
      install: pip install pre-commit
      script: pre-commit run --all-files