language: python
python:
  - "3.7"
jobs:
  include:
    - stage: "test"
      name: "pytest"
      install:
        - python setup.py install
        - pip install pytest
      script: pytest
    - stage: "test"
      name: "pre-commit"
      install: pip install pre-commit
      script: pre-commit run --all-files