language: python
python:
  - 3.8.2
  - 3.9.5
jobs:
  include:
    - stage: test
      name: pytest
      install:
        - sudo apt update && sudo apt install graphviz
        - pip install .[test]
      script: pytest
    - stage: test
      name: pre-commit
      install: pip install pre-commit
      script: pre-commit run --all-files
deploy:
  provider: pypi
  username: __token__
  skip_existing: true
  password:
    secure: STS2Spyxzazviga0dK4pm8yY7TlANh5cdOQ5Yw5KTIIs+khkNY0n9mbhrLQC26nXScUWisvDDicEpWFJbz9J8iCnFGEarsZocB6sDEhyW6vISrPiCmVRv6B2+Ys+B3104OM86YC85Jacdao+1P0og82LGLoRyEB9lzseIW1IwkA9meuq0wk5ibrzWNDvx5Qz+So33mR/ZGQ4Szl4j7H89SV58ameu/qZowiorNqHvIy+7/YDn1RZT505K5pZ31aFDlUjefIs/2stX0imt1gpO/v6myJOU16CvbdCF5o91RC9PTVu8s/UXgKUB9cUS8ouXFZTLMmMjNNHCMrdxcqHmx6Acq2jjCcjWhs+Oydb6K7Fi03mihjAKiY7i69FtSSi7fg/X+MvB5W0DDHCGfTIKU94yaKMn9OZgK7sHBfUy5J4HBxGJpbwOSMqNEVJGXsBuLHbjcgDCPfyEL+w23DdguyxkjWSa9wzsRtCpdeSr3OFCuzMm0BVouHnGUuH2Uii56wkbMMpJGu9rnPNKYQsZWehvx5q556s2wIXzXfFxxf/ByVPQ6vT97qDO0JAovcjbdfqjzGT7x3H+t82IPrSm87y6s1Odnm+x04udke7snw2aIsKhwPFYC+UKFolwNwhOqdF+ddjhKCk/rSz9GCV99r+wC+og7XkSHUxfj4WKTo=
